services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todos
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  todoservice:
    build: ./TodoService
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      POSTGRES_CONN: Host=postgres;Port=5432;Database=todos;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
