name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  packages: write   # разрешаем пушить в GHCR

jobs:
  build-test-and-image:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: todos
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            echo "Postgres is not ready yet... ($i)"
            sleep 2
          done

      - name: Restore
        run: |
          dotnet restore TodoService/TodoService.csproj
          dotnet restore TodoService.Tests/TodoService.Tests.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        env:
          ConnectionStrings__Default: Host=localhost;Port=5432;Database=todos;Username=postgres;Password=postgres
        run: dotnet test TodoService.Tests/TodoService.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/test_results.trx'

      # --------- GHCR PUSH ---------
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # (Опционально) генерируем удобные теги: sha, semver, latest на main
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/todoservice
          tags: |
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
            # если будут релизы с тегами v1.2.3 – автоматом добавит 1.2.3, 1.2, 1
            type=semver,pattern={{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push to GHCR
        uses: docker/build-push-action@v6
        with:
          context: ./TodoService
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}