name: CI

on:
  push:
    branches:
      - '**'            # все ветки (feature/*, bugfix/*, main, master)
  pull_request:
    branches: [ 'main', 'master' ]

permissions:
  contents: read
  packages: write   # нужно для GHCR push (актуально только в publish-image)

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: todos
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            echo "Postgres is not ready yet... ($i)"
            sleep 2
          done

      - name: Restore
        run: |
          dotnet restore TodoService/TodoService.csproj
          dotnet restore TodoService.Tests/TodoService.Tests.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        env:
          # Важно: используем то же имя, что в Program.cs — DefaultConnection
          ConnectionStrings__DefaultConnection: Host=localhost;Port=5432;Database=todos;Username=postgres;Password=postgres
          DOTNET_ENVIRONMENT: Development
        run: dotnet test TodoService.Tests/TodoService.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/test_results.trx'

  publish-image:
    # Только push в main/master
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/todoservice
          tags: |
            type=sha
            type=raw,value=latest
            # если будут релизы с тегами v1.2.3 — автоматом добавит 1.2.3, 1.2, 1
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}

      - name: Build & Push to GHCR
        uses: docker/build-push-action@v6
        with:
          context: ./TodoService
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
